
# ~/.config/starship.toml

[golang]
symbol = ' '

[os.symbols]
Ubuntu = " "

[custom.flenv_loaded]
command = "echo $FLENV_ENVIRONMENT"
when = "test -n \"$FLENV_ENVIRONMENT\""
style = "bold yellow"
format = "[<flenv:$output>]($style) "

[custom.flenv_cli_load]
command = "echo $FLENV_STAGE_ENVIRONMENT"
when = "test -n \"$FLENV_STAGE_ENVIRONMENT\""
style = "bold yellow"
format = "[<flenv:$output>]($style) "

[custom.tmsmono_loaded]
command = "echo $BITZYENV"
when = "test -n \"$BITZYENV\""
style = "bold yellow"
format = "[<bitzytms:$output>]($style) "
